version: "3.8"

services:
  db:
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d go_auth_db"]
      interval: 5s
      retries: 5
      timeout: 3s

  migrate:
    image: migrate/migrate
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    env_file:
      - .env  # ✅ Load environment variables for migration
    command: ["-path", "/migrations", "-database", "${DATABASE_URL}", "up"]
    links:
      - db

  app:
    build: .
    depends_on:
      migrate:
        condition: service_completed_successfully
    env_file:
      - .env  # ✅ Load environment variables for the app
    ports:
      - "8080:8080"
    networks:
      - default

networks:
  default:
    driver: bridge
