version: "3.8"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "0663058639"
      POSTGRES_DB: go_auth_db
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d go_auth_db"]
      interval: 5s
      retries: 5
      timeout: 3s

  migrate:
        image: migrate/migrate
        depends_on:
          db:
            condition: service_healthy
        volumes:
            - ./migrations:/migrations
        command: ["-path", "/migrations", "-database",  "postgres://postgres:0663058639@db:5432/go_auth_db?sslmode=disable", "up"]
        links: 
            - db
  app:
    build: .
    depends_on:
      migrate:
        condition: service_completed_successfully

    environment:
      DATABASE_URL: "postgres://postgres:0663058639@db:5432/go_auth_db?sslmode=disable"
    ports:
      - "8080:8080"
    networks:
      - default

networks:
  default:
    driver: bridge
